// import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="block w-full h-full">
        <div className="block bg-glay-300 w-full h-full">
          <div className="bg-pink-300 flex h-16 fixed w-full"></div>
          <div className="flex">
            <div></div>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
